name: Canary Web Build

on:
  push:
    branches: ["main"]
    paths:
      - "package.json"
      - "bun.lock"
      - "web/**"
      - ".forgejo/workflows/canary-web-build.yaml"
      - ".forgejo/workflows/reusable-docker-publish.yaml"
      - ".forgejo/workflows/release-build.yaml"
  workflow_dispatch:

jobs:
  docker-web:
    runs-on: docker-amd64-dind
    uses: ./.forgejo/workflows/reusable-docker-publish.yaml
    secrets: inherit
    with:
      dockerfile: ./web/Dockerfile
      target: final
      platforms: linux/amd64,linux/arm64
      images: |
        forgejo.alexma.top/alexma233/composia-web
        ghcr.io/alexma233/composia-web
      tags: |
        type=raw,value=canary-{{sha}},enable=true
        type=raw,value=canary,enable=true
      labels: |
        org.opencontainers.image.description=Composia web interface image
        org.opencontainers.image.documentation=https://docs.composia.xyz
        org.opencontainers.image.vendor=alexma233
        org.opencontainers.image.ref.name=canary
        org.opencontainers.image.version=canary-{{sha}}
        io.composia.channel=canary
      cache_ref: forgejo.alexma.top/alexma233/composia-web:buildcache
