name: Main Lint

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "bun.lock"
      - "web/**"
      - ".forgejo/workflows/main-lint.yaml"
  workflow_dispatch:

jobs:
  gofmt:
    runs-on: docker-amd64
    container:
      image: forgejo.alexma.top/alexma233/ci-images-go-node:1.26.2

    steps:
      - name: Checkout
        # renovate: datasource=git-refs depName=actions/checkout packageName=https://forgejo.alexma.top/actions/checkout currentValue=v6.0.2
        uses: https://forgejo.alexma.top/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Check Go formatting
        run: test -z "$(git ls-files '*.go' | xargs -r gofmt -l)"

  web-format:
    runs-on: docker-amd64
    container:
      image: oven/bun:1.3.12

    steps:
      - name: Checkout
        # renovate: datasource=git-refs depName=actions/checkout packageName=https://forgejo.alexma.top/actions/checkout currentValue=v6.0.2
        uses: https://forgejo.alexma.top/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Install web dependencies
        run: bun install --frozen-lockfile

      - name: Run web format checks
        run: bun run web:format
