name: Release Docker Build

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY_HOST: forgejo.alexma.top
  FORGEJO_BACKEND_IMAGE_NAME: forgejo.alexma.top/${{ github.repository }}
  FORGEJO_WEB_IMAGE_NAME: forgejo.alexma.top/${{ github.repository_owner }}/composia-web
  GHCR_BACKEND_IMAGE_NAME: ghcr.io/${{ github.repository }}
  GHCR_WEB_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/composia-web
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  docker-backend:
    runs-on: docker-amd64-dind
    steps:
      - name: Checkout
        # renovate: datasource=git-refs depName=actions/checkout packageName=https://forgejo.alexma.top/actions/checkout currentValue=v4
        uses: https://forgejo.alexma.top/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Docker Buildx
        id: buildx
        # renovate: datasource=git-refs depName=actions/docker-setup-buildx-action packageName=https://forgejo.alexma.top/actions/docker-setup-buildx-action currentValue=v3
        uses: https://forgejo.alexma.top/actions/docker-setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login to Forgejo Registry
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v3
        uses: https://forgejo.alexma.top/actions/docker-login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Login to GHCR
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v3
        uses: https://forgejo.alexma.top/actions/docker-login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker meta
        id: meta
        # renovate: datasource=git-refs depName=actions/docker-metadata-action packageName=https://forgejo.alexma.top/actions/docker-metadata-action currentValue=v5
        uses: https://forgejo.alexma.top/actions/docker-metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: |
            ${{ env.FORGEJO_BACKEND_IMAGE_NAME }}
            ${{ env.GHCR_BACKEND_IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},enable=true
            type=semver,pattern={{major}}.{{minor}},enable=true
            type=semver,pattern={{major}},enable=true
          labels: |
            org.opencontainers.image.description=Composia controller runtime image
            org.opencontainers.image.documentation=https://docs.composia.xyz
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}

      - name: Build and push
        # renovate: datasource=git-refs depName=actions/docker-build-push-action packageName=https://forgejo.alexma.top/actions/docker-build-push-action currentValue=v5
        uses: https://forgejo.alexma.top/actions/docker-build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.FORGEJO_BACKEND_IMAGE_NAME }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.FORGEJO_BACKEND_IMAGE_NAME }}:buildcache,mode=max

  docker-web:
    runs-on: docker-amd64-dind
    steps:
      - name: Checkout
        # renovate: datasource=git-refs depName=actions/checkout packageName=https://forgejo.alexma.top/actions/checkout currentValue=v4
        uses: https://forgejo.alexma.top/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Docker Buildx
        id: buildx
        # renovate: datasource=git-refs depName=actions/docker-setup-buildx-action packageName=https://forgejo.alexma.top/actions/docker-setup-buildx-action currentValue=v3
        uses: https://forgejo.alexma.top/actions/docker-setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login to Forgejo Registry
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v3
        uses: https://forgejo.alexma.top/actions/docker-login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Login to GHCR
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v3
        uses: https://forgejo.alexma.top/actions/docker-login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker meta
        id: meta
        # renovate: datasource=git-refs depName=actions/docker-metadata-action packageName=https://forgejo.alexma.top/actions/docker-metadata-action currentValue=v5
        uses: https://forgejo.alexma.top/actions/docker-metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: |
            ${{ env.FORGEJO_WEB_IMAGE_NAME }}
            ${{ env.GHCR_WEB_IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},enable=true
            type=semver,pattern={{major}}.{{minor}},enable=true
            type=semver,pattern={{major}},enable=true
          labels: |
            org.opencontainers.image.description=Composia web interface image
            org.opencontainers.image.documentation=https://docs.composia.xyz
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}

      - name: Build and push
        # renovate: datasource=git-refs depName=actions/docker-build-push-action packageName=https://forgejo.alexma.top/actions/docker-build-push-action currentValue=v5
        uses: https://forgejo.alexma.top/actions/docker-build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          file: ./web/Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.FORGEJO_WEB_IMAGE_NAME }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.FORGEJO_WEB_IMAGE_NAME }}:buildcache,mode=max
