name: Release Build

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY_HOST: forgejo.alexma.top
  FORGEJO_BACKEND_IMAGE_NAME: forgejo.alexma.top/${{ github.repository }}
  FORGEJO_WEB_IMAGE_NAME: forgejo.alexma.top/${{ github.repository_owner }}/composia-web
  GHCR_BACKEND_IMAGE_NAME: ghcr.io/${{ github.repository }}
  GHCR_WEB_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/composia-web
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  docker-backend:
    runs-on: docker-amd64-dind
    steps:
      - name: Checkout
        # renovate: datasource=git-refs depName=actions/checkout packageName=https://forgejo.alexma.top/actions/checkout currentValue=v6.0.2
        uses: https://forgejo.alexma.top/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Docker Buildx
        id: buildx
        # renovate: datasource=git-refs depName=actions/docker-setup-buildx-action packageName=https://forgejo.alexma.top/actions/docker-setup-buildx-action currentValue=v4.0.0
        uses: https://forgejo.alexma.top/actions/docker-setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to Forgejo Registry
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v4.1.0
        uses: https://forgejo.alexma.top/actions/docker-login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Login to GHCR
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v4.1.0
        uses: https://forgejo.alexma.top/actions/docker-login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker meta
        id: meta
        # renovate: datasource=git-refs depName=actions/docker-metadata-action packageName=https://forgejo.alexma.top/actions/docker-metadata-action currentValue=v6.0.0
        uses: https://forgejo.alexma.top/actions/docker-metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: |
            ${{ env.FORGEJO_BACKEND_IMAGE_NAME }}
            ${{ env.GHCR_BACKEND_IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},enable=true
            type=semver,pattern={{major}}.{{minor}},enable=true
            type=semver,pattern={{major}},enable=true
          labels: |
            org.opencontainers.image.description=Composia controller runtime image
            org.opencontainers.image.documentation=https://docs.composia.xyz
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}

      - name: Build and push
        # renovate: datasource=git-refs depName=actions/docker-build-push-action packageName=https://forgejo.alexma.top/actions/docker-build-push-action currentValue=v7.1.0
        uses: https://forgejo.alexma.top/actions/docker-build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.FORGEJO_BACKEND_IMAGE_NAME }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.FORGEJO_BACKEND_IMAGE_NAME }}:buildcache,mode=max

  docker-web:
    runs-on: docker-amd64-dind
    steps:
      - name: Checkout
        # renovate: datasource=git-refs depName=actions/checkout packageName=https://forgejo.alexma.top/actions/checkout currentValue=v6.0.2
        uses: https://forgejo.alexma.top/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Docker Buildx
        id: buildx
        # renovate: datasource=git-refs depName=actions/docker-setup-buildx-action packageName=https://forgejo.alexma.top/actions/docker-setup-buildx-action currentValue=v4.0.0
        uses: https://forgejo.alexma.top/actions/docker-setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to Forgejo Registry
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v4.1.0
        uses: https://forgejo.alexma.top/actions/docker-login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Login to GHCR
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v4.1.0
        uses: https://forgejo.alexma.top/actions/docker-login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker meta
        id: meta
        # renovate: datasource=git-refs depName=actions/docker-metadata-action packageName=https://forgejo.alexma.top/actions/docker-metadata-action currentValue=v6.0.0
        uses: https://forgejo.alexma.top/actions/docker-metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: |
            ${{ env.FORGEJO_WEB_IMAGE_NAME }}
            ${{ env.GHCR_WEB_IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},enable=true
            type=semver,pattern={{major}}.{{minor}},enable=true
            type=semver,pattern={{major}},enable=true
          labels: |
            org.opencontainers.image.description=Composia web interface image
            org.opencontainers.image.documentation=https://docs.composia.xyz
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.ref.name=${{ github.ref_name }}

      - name: Build and push
        # renovate: datasource=git-refs depName=actions/docker-build-push-action packageName=https://forgejo.alexma.top/actions/docker-build-push-action currentValue=v7.1.0
        uses: https://forgejo.alexma.top/actions/docker-build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          file: ./web/Dockerfile
          push: true
          platforms: ${{ env.PLATFORMS }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.FORGEJO_WEB_IMAGE_NAME }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.FORGEJO_WEB_IMAGE_NAME }}:buildcache,mode=max
