name: Reusable Docker Publish

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      target:
        required: true
        type: string
      platforms:
        required: true
        type: string
      images:
        required: true
        type: string
      tags:
        required: true
        type: string
      labels:
        required: true
        type: string
      cache_ref:
        required: true
        type: string
      latest:
        default: false
        required: false
        type: boolean
      login_dockerhub:
        default: false
        required: false
        type: boolean

env:
  REGISTRY_HOST: forgejo.alexma.top

jobs:
  publish:
    runs-on: docker-amd64-dind
    steps:
      - name: Checkout
        # renovate: datasource=git-refs depName=actions/checkout packageName=https://forgejo.alexma.top/actions/checkout currentValue=v6.0.2
        uses: https://forgejo.alexma.top/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Docker Buildx
        id: buildx
        # renovate: datasource=git-refs depName=actions/docker-setup-buildx-action packageName=https://forgejo.alexma.top/actions/docker-setup-buildx-action currentValue=v4.1.0
        uses: https://forgejo.alexma.top/actions/docker-setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5

      - name: Login to Forgejo Registry
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v4.2.0
        uses: https://forgejo.alexma.top/actions/docker-login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ secrets.OCI_IMAGES_FORGEJO_USERNAME }}
          password: ${{ secrets.OCI_IMAGES_FORGEJO_TOKEN }}

      - name: Login to GHCR
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v4.2.0
        uses: https://forgejo.alexma.top/actions/docker-login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          registry: ghcr.io
          username: ${{ secrets.OCI_IMAGES_GHCR_USERNAME }}
          password: ${{ secrets.OCI_IMAGES_GHCR_TOKEN }}

      - name: Login to Docker Hub
        if: ${{ inputs.login_dockerhub }}
        # renovate: datasource=git-refs depName=actions/docker-login-action packageName=https://forgejo.alexma.top/actions/docker-login-action currentValue=v4.2.0
        uses: https://forgejo.alexma.top/actions/docker-login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
        with:
          username: ${{ secrets.OCI_IMAGES_DOCKERHUB_USERNAME }}
          password: ${{ secrets.OCI_IMAGES_DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        # renovate: datasource=git-refs depName=actions/docker-metadata-action packageName=https://forgejo.alexma.top/actions/docker-metadata-action currentValue=v6.1.0
        uses: https://forgejo.alexma.top/actions/docker-metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
        with:
          images: ${{ inputs.images }}
          flavor: |
            latest=${{ inputs.latest }}
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}

      - name: Build and push
        # renovate: datasource=git-refs depName=actions/docker-build-push-action packageName=https://forgejo.alexma.top/actions/docker-build-push-action currentValue=v7.2.0
        uses: https://forgejo.alexma.top/actions/docker-build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          target: ${{ inputs.target }}
          push: true
          platforms: ${{ inputs.platforms }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ inputs.cache_ref }}
          cache-to: |
            type=registry,ref=${{ inputs.cache_ref }},mode=max
