root = "."
tmp_dir = "/tmp/air-agent"

[build]
cmd = "go build -buildvcs=false -o /tmp/air-agent/composia ./cmd/composia"
bin = "/tmp/air-agent/composia"
args_bin = ["agent", "-config", "./dev/config.controller.container.yaml"]
include_ext = ["go", "yaml", "yml"]
exclude_dir = [
  ".git",
  "docs",
  "dev/.bun-cache-user",
  "dev/.go-build-cache",
  "dev/.go-mod-cache",
  "dev/.node_modules-user",
  "dev/.web-node_modules-user",
  "dev/bun-cache",
  "dev/bun-cache-user",
  "dev/go-build-cache",
  "dev/go-mod-cache",
  "dev/logs",
  "dev/node_modules",
  "dev/node_modules-user",
  "node_modules",
  "dev/repo-agent",
  "dev/repo-controller",
  "dev/state-agent",
  "dev/state-controller",
  "dev/web-node_modules",
  "dev/web-node_modules-user",
  "web",
  "web/node_modules",
]
delay = 500
stop_on_error = true

[log]
time = true
