services:
  controller-dev:
    build:
      context: ..
      target: dev
    working_dir: /workspace
    environment:
      GIT_CONFIG_COUNT: "2"
      GIT_CONFIG_KEY_0: safe.directory
      GIT_CONFIG_VALUE_0: /data/repo-controller
      GIT_CONFIG_KEY_1: safe.directory
      GIT_CONFIG_VALUE_1: /workspace
    command:
      - sh
      - -c
      - |
        mkdir -p /data/repo-controller /data/state-controller /data/logs
        if [ ! -d /data/repo-controller/.git ]; then
          git init -q /data/repo-controller
        fi
        /go/bin/air -c ./dev/air.controller.toml
    ports:
      - "7001:7001"
    volumes:
      - ${DEV_WORKSPACE_DIR}:/workspace
      - ./repo-controller:/data/repo-controller
      - ./state-controller:/data/state-controller
      - ./logs:/data/logs
      - ${DEV_GO_MOD_CACHE_DIR}:/go/pkg/mod
      - ${DEV_GO_BUILD_CACHE_DIR}:/root/.cache/go-build
    networks:
      - composia-dev

  agent-dev:
    build:
      context: ..
      target: dev
    depends_on:
      controller-dev:
        condition: service_started
    working_dir: /workspace
    environment:
      GIT_CONFIG_COUNT: "2"
      GIT_CONFIG_KEY_0: safe.directory
      GIT_CONFIG_VALUE_0: /data/repo-agent
      GIT_CONFIG_KEY_1: safe.directory
      GIT_CONFIG_VALUE_1: /workspace
    command:
      - sh
      - -c
      - |
        mkdir -p /data/repo-agent /data/state-agent
        /go/bin/air -c ./dev/air.agent.toml
    volumes:
      - ${DEV_WORKSPACE_DIR}:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ./repo-agent:/data/repo-agent
      - ./state-agent:/data/state-agent
      - ${DEV_GO_MOD_CACHE_DIR}:/go/pkg/mod
      - ${DEV_GO_BUILD_CACHE_DIR}:/root/.cache/go-build
    networks:
      - composia-dev

  web-dev:
    image: denoland/deno:2.9.2@sha256:69a9f3033e3f381770452648b1cbf4ae96ea409f7ef24f30afeff3d380705f62
    user: "${UID}:${GID}"
    entrypoint:
      - sh
      - -lc
    depends_on:
      controller-dev:
        condition: service_started
    working_dir: /workspace
    command: deno install && deno task web:dev -- --host 0.0.0.0 --port 5173
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    volumes:
      - ${DEV_WORKSPACE_DIR}:/workspace
      - ${DEV_DENO_CACHE_DIR}:/deno-dir
      - ${DEV_ROOT_NODE_MODULES_DIR}:/workspace/node_modules
      - ${DEV_WEB_NODE_MODULES_DIR}:/workspace/web/node_modules
    networks:
      - composia-dev

  docs-dev:
    image: forgejo.alexma.top/alexma233/ci-images-hugo-wrangler:0.164.0@sha256:223c5fb468fca4b632fe5e09020c18b48e225aa356c4d7ac83ec1ff81a3a1d90
    user: "${UID}:${GID}"
    profiles:
      - docs
    working_dir: /workspace
    command:
      - sh
      - -lc
      - hugo serve --port 5174 -s site --bind 0.0.0.0
    ports:
      - "5174:5174"
    volumes:
      - ${DEV_WORKSPACE_DIR}:/workspace
    networks:
      - composia-dev

networks:
  composia-dev:
    name: composia-dev
