services:
  n8n:
    image: "${IMAGE_REPOSITORY:-docker.n8n.io}/n8nio/n8n:${SERVER_VERSION:-latest}"
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - N8N_PROXY_HOPS=1
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - data:/home/node/.n8n
      # - ./local-files:/files
volumes:
  data:
    name: "n8n_data"
