name: lobe-chat-database
services:
  database:
    image: pgvector/pgvector:pg16
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  server:
    image: "${IMAGE_REPOSITORY:-docker.io}/lobehub/lobe-chat-database:${SERVER_VERSION:-latest}"
    ports:
      - 127.0.0.1:3210:3210
    depends_on:
      - database
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - nc
        - -z
        - 127.0.0.1
        - "3210"
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  database_data:
    name: "lobechat_database_data"
