services:
  redis:
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - redis_data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
  server:
    image: "${IMAGE_REPOSITORY:-docker.io}/searxng/searxng:${SERVER_VERSION:-latest}"
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - 127.0.0.1:29321:8080
    volumes:
      - server_config:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  searxng: null
volumes:
  redis_data:
    name: "searxng_redis_data"
  server_config:
    name: "searxng_server_config"
